apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
    app: mysql-pvc
spec:
  selector:
    matchLabels:
      app: mysql-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi