apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: docker-manager
  name: docker-manager
spec:
  replicas: 1  #pod副本数
  selector:
    matchLabels:
      app: docker-manager
  template:
    metadata:
      labels:
        app: docker-manager
    spec:
      tolerations:	#设置节点容忍度
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
      hostAliases:
        - hostnames: #设置pod内host解析
            - mysql
          ip: 1.94.9.77
        - hostnames:
            - redis
          ip: 1.94.9.77
      containers:
        - image: mysql:latest
          imagePullPolicy: IfNotPresent
          name: web-mysql
          ports:
            - containerPort: 3306
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - /path/to/mysql-healthcheck.sh
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - /path/to/mysql-healthcheck.sh
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
              - name: MYSQL_ROOT_PASSWORD
                value: o?dv(%qn)Uf8*e^3AQTPB4k6L1N975xG

          volumeMounts: #挂载PV
            - name: mysql-data
              mountPath: /web/mysql


        - image: redis:latest
          imagePullPolicy: IfNotPresent
          name: web-redis
          ports:
            - containerPort: 6379
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - /path/to/redis-healthcheck.sh
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - /path/to/redis-healthcheck.sh
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
            - name: REDIS_PASSWORD
              value: o?dv(%qn)Uf8*e^3AQTPB4k6L1N975xG
          volumeMounts: #挂载PV
            - name: redis-data
              mountPath: /web/redis


        - image: images/web
          imagePullPolicy: IfNotPresent
          name: web-service
          livenessProbe:	#健康检查
            httpGet:   # tcpSocket
              path: /
              port: 80
            initialDelaySeconds: 60	#pod初始化时间
            timeoutSeconds: 20
          readinessProbe:	#健康检查
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 60
            timeoutSeconds: 20
          resources:  #资源限制
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 10Mi
          volumeMounts: #挂载PV
            - name: web-logs
              mountPath: /web/logs


      volumes:
        - name: web-logs #声明PV
          hostPath:
            path: /web/logs
            type: Directory
        - name: mysql-data #声明PV
          hostPath:
            path: /web/mysql
            type: Directory
        - name: redis-data #声明PV
          hostPath:
            path: /web/redis
            type: Directory


