version: "3"
services:
  mysql:
    image: mysql:8.3.0
    ports:
      - "1763:3306"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/data:/var/lib/mysql
      - ./mysql/log:/var/log
    networks:
      - dbNetwork
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=o?dv(%qn)Uf8*e^3AQTPB4k6L1N975xG

  redis:
    image: redis:7.2.4
    command: redis-server /etc/redis/redis.conf
    ports:
      - "1764:6379"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - dbNetwork
    volumes:
      - ./redis/conf:/etc/redis
      - ./redis/data:/data/data
      - ./redis/log:/data/log
    environment:
      - TZ=Asia/Shanghai
networks:
  dbNetwork: