version: "3"

services:
  mysql1:
    image: mysql
    networks:
      - mysqlService
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - ./mysql1/data:/var/lib/mysql #权限必须是可执行的，否者mysql无法向文件夹写入
      - ./mysql1/log:/var/log #权限必须是可执行的，否者mysql无法向文件夹写入
      - ./mysql1/conf/mysqld.cnf:/etc/my.cnf #权限必须是只读的，否则不会应用该配置
  mysql2:
    image: mysql
    networks:
      - mysqlService
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - ./mysql2/data:/var/lib/mysql #权限必须是可执行的，否者mysql无法向文件夹写入
      - ./mysql2/log:/var/log #权限必须是可执行的，否者mysql无法向文件夹写入
      - ./mysql2/conf/mysqld.cnf:/etc/my.cnf #权限必须是只读的，否则不会应用该配置
networks:
  mysqlService: