##pv 配置， 使用nfs文件系统
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: mysql1-data-pv
#  namespace: mysql
#spec:
#  capacity:
#    storage: 1Gi
#  accessModes:
#    - ReadWriteOnce
#  nfs:
#    server: 192.168.30.198
#    path: /deployments/db_deployments/mysql/mysql1/data
#---
##pvc 配置
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: mysql1-data-pvc
#  namespace: mysql
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 1Gi
#---
##service 配置
#apiVersion: v1
#kind: Service
#metadata:
#  name: mysql-service
#  namespace: mysql
#spec:
#  selector:
#    app: mysql-pod
#  ports:
#    - protocol: TCP
#      port: 3306 #service暴露的端口
#      targetPort: 3306 #pod的端口
#  type: ClusterIP
#---
##pv 配置， 使用nfs文件系统
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: mysql2-data-pv
#  namespace: mysql
#spec:
#  capacity:
#    storage: 1Gi
#  accessModes:
#    - ReadWriteOnce
#  nfs:
#    server: 192.168.30.198
#    path: /deployments/db_deployments/mysql/mysql2/data
#---
##pvc 配置
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: mysql2-data-pvc
#  namespace: mysql
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 1Gi
---
apiVersion: v1
kind: Namespace
metadata:
  name: mysql
  labels:
    app: mysql
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: mysql
  labels:
    app: mysql
data:
  master.cnf: |
    # Master配置
    [mysqld]
    log-bin=mysqllog
    skip-name-resolve
  slave.cnf: |
    # Slave配置
    [mysqld]
    super-read-only
    skip-name-resolve
    log-bin=mysql-bin
    replicate-ignore-db=mysql
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysql
  labels:
    app: mysql
type: Opaque
data:
  password: MTIzNDU2 # echo -n "123456" | base64
---
#pv 配置， 使用nfs文件系统
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-data-pv
  namespace: mysql
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.30.198
    path: /deployments/db_deployments/mysql/mysql/data
---
#pvc 配置
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data-pvc
  namespace: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: mysql
  labels:
    app: mysql
spec:
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
  selector:
    app: mysql
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-read
  namespace: mysql
  labels:
    app: mysql
spec:
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
  selector:
    app: mysql
  type: ClusterIP