#pv 配置， 使用nfs文件系统
apiVersion: v1
kind: PersistentVolume
metadata:
  name: web-pv
  namespace: web
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.30.198
    path: /deployments/web/share
---
#pvc 配置
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi